version: '3.1'
services:
  database:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_DB=scraper
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_ROOT_PASSWORD=rootpassword
    # volumes:
    #   - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080